version: "3"

# Networks is used to create a network and ip addresses for containers.
# These are used to prevent dynamic ip addresses from being assigned to
# containers.
networks:
  cursus-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.26.0.0/24"

services:
  web:
    container_name: web-container
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    ports:
      - "5000:5001"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./cursus:/cursus/cursus
    restart: always
    networks:
      cursus-network:
        ipv4_address: 172.26.0.3

  postgres:
    container_name: postgres-container
    image: postgres:15
    env_file: .env
    ports:
      - "7432:7432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    networks:
      cursus-network:
        ipv4_address: 172.26.0.2

  redis:
    container_name: redis-container
    image: redis:6.2.6
    env_file: .env
    ports:
      - "6379:6379"
    restart: always
    networks:
      cursus-network:
        ipv4_address: 172.26.0.4

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "5050:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always
    depends_on:
      - postgres
    networks:
      cursus-network:
        ipv4_address: 172.26.0.5

  nginx:
    container_name: nginx-container
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    environment:
      - APP_SERVER_UPSTREAM=cursus-web
      - APP_SERVER_SERVICE=web-container
      - APP_SERVER_PORT=5001
      - APP_ADMIN_UPSTREAM=cursus-pgadmin
      - APP_ADMIN_SERVICE=pgadmin-container
      - APP_ADMIN_PORT=5050
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - web
      - postgres
      - pgadmin
    networks:
      cursus-network:
        ipv4_address: 172.26.0.6

volumes:
  postgres_data:
  pgadmin_data:
